### ISSUE TITLE
[Testlio][Desktop][Compliance standards] 'You have no access to organization standards' error occurs after clicking the '<' button in the header

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#218] opened 2016-10-19 14:34 UTC
**Environment:**
Device and OS: Windows 10; Microsoft Edge 38.14393.0.0
Testable App version: https://app.pliohub.com v0.2.37
Network: WiFi
Location: Ukraine
Reproducibility rate: 5/5

**Steps to reproduce:** 
1. Click the 'Compliance standards'
2. Click the '<' (back) button

**Expected result:**
Possible to return to the previous page without any issues

**Actual result:** 
'You have no access to organization standards' error occurs after clicking the '<' button in the header<p><a href="https://testlio.s3.amazonaws.com/issue/145607/a/e8908206-77eb-79ec-6354-32845895a17e/cc5ac6851c61c42ee90bb08d30b17f5e.mp4">error_back.mp4</a><br><img src="https://testlio.s3.amazonaws.com/issue/145607/a/e97e38ba-644e-65da-6a67-53dcde5fe0b6-medium.jpg"/><br></p>

**Comment by Praxie** [comment] 2016-10-25 09:13
@RevelsGit can you reproduce this bug in Edge?

**Comment by RevelsGit** [comment] 2016-10-25 09:48
@Praxie yes

**Comment by Praxie** [comment] 2016-10-25 14:28
@RevelsGit What's going on there? Is the sequenceId undefined?

**Comment by RevelsGit** [comment] 2016-10-27 13:32
I cannot reproduce this bug anymore. I think it is fixed with the new release.

**Closed** 2016-11-04 14:20 UTC
Labels: bug, can't be reproduced, testlio

**Comment by markokruustuk** [comment] 2016-11-04 14:24
Closed from GitHub
