### ISSUE TITLE
Overdue work item bug

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#2094] opened 2019-08-12 08:21 UTC
In the organization "Plio Ltd" the overdue work items section is showing one item as overdue for user Stephen Ives (see below), NC92 Test 2.  However, when opening the Work Inbox for Stephen Ives, there are no overdue work items displaying (see screenshot below).  When opening the Nonconformities screen it is apparent that there is no NC92.  I can only find records of 10 NCs that have previously been created.  However, when I create a new NC called "Test" this is numbered as NC94.  

I looked at a couple of other organizations and the numbering of work items on the home screen and in the Work Inbox seems to be fine, so this problem may be specific to Plio Ltd (or it may not - I haven't had time to do an exhaustive analysis).

So there seem to be 2 problems:
1. Incorrect reporting of overdue work items on home screen for the Plio Ltd organization
2. When and how did NCs in the range NC10 - NC93 get created for Plio Ltd? There is no record of them in the organization.

![Screenshot 2019-08-12 at 09 04 19](https://user-images.githubusercontent.com/2330529/62852810-6c78d600-bce2-11e9-9358-001dd7f0a622.png)

![Screenshot 2019-08-12 at 09 04 29](https://user-images.githubusercontent.com/2330529/62852818-739fe400-bce2-11e9-8f42-f5b310e7f446.png)

**Comment by michaelrokosh** [comment] 2019-08-14 11:47
Hi @sives 
1. There is a a related work item, you're probably signed in as a different user. 
![image](https://user-images.githubusercontent.com/2095940/63018783-59acff80-bea2-11e9-9a34-0fe5a06fff08.png)

2. There are about 80 deleted NCs in the Plio organization. That's why the ID is NC92.
![image](https://user-images.githubusercontent.com/2095940/63018712-37b37d00-bea2-11e9-9ea4-f8577847439c.png)

**Comment by sives** [comment] 2019-08-14 18:30
@michaelrokosh Regarding the 2 problems I stated above:

1. I was definitely not signed in as a different user, but as Steve Ives
The root cause of the problem is apparent from the screenshot you posted above.
NC92 was deleted by user = "ghost" on June 11th 2019 and for some reason still shows up partially in my workspace.

2. You are right, all these items are in my deleted items view.  So ignore this - it is a non-problem.

**Comment by michaelrokosh** [comment] 2019-08-16 11:24
@sives I'm closing it because now we found the root cause and I created a more clear issue:
https://github.com/Pliohub/Plio/issues/2099

**Closed by michaelrokosh** 2019-08-16 11:24 UTC
Labels: bug
