### ISSUE TITLE
The colour palette is incorrect

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1659] opened 2018-12-18 12:49 UTC
> The colour palette is incorrect - it was updated a long time ago in the UI prototype to include grey and Post-it yellow (see UI prototype)

There should be an issue for this already.

**Comment by Dartv** [comment] 2018-12-18 13:37
duplicate of #1444

**Comment by sives** [comment] 2019-01-15 10:31
Looks good!

**Closed by sives** 2019-01-15 10:31 UTC
Labels: to be tested by customer
