### ISSUE TITLE
User Directory router bug

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#2006] opened 2019-04-05 16:52 UTC
https://youtu.be/7IC8rjlBaxE

1. Go to the User Directory.
2. Remove the user.
3. *The router sets backRoute=userDirectoryPage*.
4. After clicking on the "back" button, the users is redirected to the same screen with no user selected. Now he's stuck and can't select any user in the LHS section or go back to the home screen.

**The suggested fix would be to prevent setting backRoute to the current route.**

**Comment by Dartv** [comment] 2019-04-05 19:56
duplicate of https://github.com/Pliohub/Plio/issues/2005

**Closed by Dartv** 2019-04-05 19:56 UTC
Labels: bug

**Comment by Dartv** [comment] 2019-04-06 03:01
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 04/05/19 - 04/05/19
Work session total: 0:47:31

Grand total: 0:47:31
