### ISSUE TITLE
Add an "autocomplete" attribute for inputs and set it to "off"

### ISSUE THREAD

**Issue by Praxie** [Pliohub/Plio#1669] opened 2018-12-18 13:53 UTC
Steve reported that the dropdown appears when he tries to set the title for the section item. I can't reproduce this but we need to set autocomplete to the off state in all text inputs.

"The autocomplete attribute specifies whether a form should have autocomplete on or off. When autocomplete is on, the browser automatically complete values based on values that the user has entered before. Tip: It is possible to have autocomplete "on" for the form, and "off" for specific input fields, or vice versa."

**Comment by Serhiy91** [comment] 2018-12-21 14:38
Duplicate of https://github.com/Pliohub/Plio/issues/1662

**Closed** 2019-01-04 17:10 UTC
Labels: duplicate
