### ISSUE TITLE
[Testlio][Desktop][Preventative action] Internal Server error when trying to complete PA

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#239] opened 2016-10-19 14:39 UTC
**Environment:**
Device and OS: Windows 10, Firefox 47.0.1
Testable App version:https://app.pliohub.com
Network: Wifi
Location: Cz
Reproducibility rate: 3/3

**Prerequisites:** there are not completed Preventative action assigned to user
**Steps to reproduce:** 
1. Login with valid account
2. Go to Work Inbox
3. Select any PA to complete
4. Click Complete->Confirm
5. Observe result

**Expected result:**
User should be able to complete PA without any issues

**Actual result:** 
Server error is dispalyed
<p><a href="https://testlio.s3.amazonaws.com/issue/145537/a/353e2105-81d4-4975-309d-b66e415b2c9f/ffacb946f02255dff2a2dff8bc21412c.mp4">2016-10-11 14h56_02.mp4</a><br><img src="https://testlio.s3.amazonaws.com/issue/145537/a/de2da14f-effc-9b5e-6069-4d6bc0229fe6-medium.jpg"/><br><a href="https://testlio.s3.amazonaws.com/issue/145537/a/87983e5b-3b3d-efb4-f146-5dc7bbd57d70/78fd18fe16d0fb73d2a8d6d5d081983b.mp4">2016-10-11 15h00_26.mp4</a><br></p>

**Comment by Praxie** [comment] 2016-10-26 14:02
@sives @markokruustuk I can't reproduce this bug. Maybe it's fixed now.

**Closed** 2016-10-28 09:44 UTC
Labels: bug, resolved, testlio

**Comment by markokruustuk** [comment] 2016-10-28 09:48
Closed from GitHub
