### ISSUE TITLE
[Testlio][Mobile][Compliance standard] Can't scroll fully down when keypad open. 

### ISSUE THREAD

**Issue by markokruustuk** [Pliohub/Plio#236] opened 2016-10-19 14:39 UTC
**Environment:**
Device and OS:iPhone6S iOS 10.0.2
Testable App version:https://app.pliohub.com v0.2.36
Network:WiFi
Location:Bangladesh
Reproducibility rate: 3/3

**Steps to reproduce:** 
1. Login to web.
2. Compliance standards> Add
3. Tap on any text field (i.e: Title)
4. Try to scroll fully down> Observe

**Expected result:**
Should be able to scroll smoothly everywhere.

**Actual result:** 
Can't fully scroll down when keypad open in any text field. <p><a href="https://testlio.s3.amazonaws.com/issue/145543/a/2d8651d6-cda5-fde2-81a1-c05e2fe0f7c5/50870bbd2612c2b953469cdc9f85181e.txt">26743_Log.txt</a><br><a href="https://testlio.s3.amazonaws.com/issue/145543/a/aece74f9-71fe-0bff-2ad1-8d3b9fe763c2/ae780f23a2f541ca4893f11c96dcf08e.mp4">26743_Video.mp4</a><br></p>

**Comment by Praxie** [comment] 2016-10-26 08:35
@RomanValihura please check the same behaviour on Android browser/Chrome.

**Comment by Praxie** [comment] 2016-10-26 08:37
I can't think of the solution. The user needs to close the virtual keyboard by clicking on Done or click on the nearby input element.

**Comment by RomanValihura** [comment] 2016-10-27 10:10
Cannot reproduce on my Android device.

**Comment by Praxie** [comment] 2016-11-03 11:02
@sives it's ios-related issue.

**Comment by Praxie** [comment] 2016-11-03 11:03
I still don't have a solution for this one. Hopefully it's not a big issue.

**Comment by sives** [comment] 2016-11-04 14:00
Not a big issue, let's put it on hold and close it.

**Closed by sives** 2016-11-04 14:00 UTC
Labels: bug, can't be reproduced, on hold, testlio

**Comment by markokruustuk** [comment] 2016-11-04 14:04
Closed from GitHub
