### ISSUE TITLE
Links in notification emails taking user to incorrect screen

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1112] opened 2018-05-21 10:50 UTC
Any notification that includes the phrase "to complete...." relating to a work action (e.g. "Steve Ives assigned you to complete corrective action CA40") should provide a link labelled "View work item"  and clicking on this link should take that user to the Work Inbox screen, displaying the appropriate red To Do panel, with the relevant item card underneath.   

This does not seem to be happening with Root cause analysis notifications and with Risk analysis notifications.  Clicking on the link in the NC2 email (see below) took me to the Nonconformity screen displaying the NC2 card, instead of to the Work inbox displaying the red To Do panel and the NC2 card.

![screen shot 2018-05-21 at 11 47 58](https://user-images.githubusercontent.com/2330529/40304054-1e350f14-5ced-11e8-9c76-e987176a29a0.png)

**Comment by sives** [comment] 2018-05-21 16:36
On reflection I think there are good reasons why Plio manages the first step in the workflows for NCs and Risks in this way - this is probably the intended behavour in the original design!

**Comment by Dartv** [comment] 2018-05-21 17:14
@sives I already implemented these changes. Do we need to revert them?

**Comment by sives** [comment] 2018-05-21 17:16
Sorry Dmytro, I didn't expect you to implement them so quickly!   OK, let's leave the changes in place, there are also some small benefits for the user in making these changes.

**Comment by sives** [comment] 2018-05-21 17:27
With these changes, we definitely have a better implementation than the existing one

**Comment by Dartv** [comment] 2018-05-21 17:32
Why not? This is just a normal work item. We already have a similar email when the user is assigned to do root cause analysis with "View work item" button leading to work inbox with "Complete" button presented. Why would we change that behavior for reminders?

**Comment by sives** [comment] 2018-05-21 17:37
With simple workflow items, like corrective actions and preventative actions, all the user needs to do record completion of the action is to click on a "Complete" button.

With more complex workflow items, like root cause analyses and risk analyses, it isn't sufficient for the user who has been responsibility for carrying out the workflow item just to go and click on a "Complete" button.  They've got to open the relevant NC or Risk card, and go and fill some information into the relevant section.   Giving them the option of just clicking on a "Complete" button is bad, because they won't understand that they are expected to do more than just clicking the button to complete the action.

When the user is assigned to do the root cause analysis or risk analysis in the first place, we also need to make sure that there is no "Complete"  button.

**Comment by Dartv** [comment] 2018-05-21 17:41
It should be a new issue then

**Comment by sives** [comment] 2018-05-21 17:42
Yes, I agree. I will re-classify it as a UI enhancement.

**Comment by Dartv** [comment] 2018-05-22 09:32
So do we need to get rid of this button completely for root cause analysis, initial risk analysis? What about final approval?

**Comment by sives** [comment] 2018-05-22 10:06
@Dartv @Praxie No, we just need to get rid of the button in the red To Do panel for this specific step of the workflow, associated with this specific To Do panel guidance text.  For those other steps in the workflow where the user just needs to do a single simple action, the button (with the appropriate button label) should remain in the red To Do panel.

**Comment by Praxie** [comment] 2018-05-22 11:04
@Dartv Steve meant that we should remove the button from the quick action panel on the Work inbox screen, but keep it in the editable card so that user would need to click on the Edit button to see this button.

@sives I'd suggest to keep the button in the quick action panel but display a warning alert, asking the user to confirm his action and reminding him to make sure to go to the card and do all stuff in a good way. What do you think?

**Comment by sives** [comment] 2018-05-22 11:09
For clarification, when I've described the "red To Do panel" in the comments above, it is exactly the same UI design element as the "quick action panel" that Mike has mentioned.

**Comment by Dartv** [comment] 2018-05-22 11:09
No, I already did this https://github.com/Pliohub/Plio/pull/1119 I just needed to be sure.
This button is not an immediate action. It opens modal where user can enter any completion comments and then click "Complete" button again, so it's already idiot-proof enough I feel like.

**Comment by Praxie** [comment] 2018-05-22 11:10
@sives actually yes, there is a section to input completion comments. I'm not sure if it's mandatory though.

**Comment by Dartv** [comment] 2018-05-22 11:12
It's exactly the same for actions and approval too, so I don't get why we should change this only for root cause analysis and initial risk analysis

**Comment by sives** [comment] 2018-05-22 11:15
@Praxie Completion comments are optional, not mandatory

**Comment by Dartv** [comment] 2018-05-22 11:37
What about approval? It has the same structure as root cause analysis.

**Comment by sives** [comment] 2018-05-22 11:47
I assume that you are referring to "final approval" in a 6 step workflow.   There is a subtle difference in the final approval step.  The user can get all the information they need to give final approval by looking at the read-only version of the card, there is no need to go in and edit to card to update with any additional information.  This is not true of the root cause analysis and risk analysis steps.

**Comment by Praxie** [comment] 2018-05-22 12:07
@sives so do we still need to hide the button from the quick action panel is there is an additional step of filling in the completion comments though they are not mandatory?

**Comment by sives** [comment] 2018-05-22 12:29
The benefit of the existing design (i.e. the current behaviour in the live system) is that it pushes the user directly to the relevant card in the NC or Risk screen, and forces the user to click on "Edit" before they can then go and complete the work item.  The new approach I've proposed is better still, it pushes the user to the Work inbox (which is good, because it is an item of work) but still forces the user to click on "Edit" to be able to go and complete the work item (and doesn't allow the stupid user to just click on "Complete" and bypass the updating of the card with the analysis details)

**Comment by sives** [comment] 2018-05-22 12:30
I'm available for a Skype call tomorrow if needed

**Comment by Dartv** [comment] 2018-05-22 13:51
No need, I understand what you meant

**Comment by Dartv** [comment] 2018-05-22 15:40
https://github.com/Pliohub/Plio/pull/1119

**Comment by Praxie** [comment] 2018-05-30 17:18
![screen shot 2018-05-30 at 8 17 52 pm](https://user-images.githubusercontent.com/2095940/40736380-92e5f87c-6446-11e8-8e1b-138fb9c14050.png)

**Comment by Praxie** [comment] 2018-05-30 17:18
![screen shot 2018-05-30 at 8 18 39 pm](https://user-images.githubusercontent.com/2095940/40736411-ad2b61a4-6446-11e8-8775-c1bbbc784f9b.png)

**Closed** 2018-06-29 13:13 UTC
Labels: UI enhancement, resolved

**Comment by Dartv** [comment] 2018-06-30 03:04
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/21/18 - 05/22/18
Work session total: 4:37:22

Grand total: 4:37:22
