### ISSUE TITLE
Blank item in LHS list view in Work inbox

### ISSUE THREAD

**Issue by sives** [Pliohub/Plio#1085] opened 2018-05-16 15:43 UTC
After entering 20 or more actions into the Shift Bioscience organisation, nonconformities and risks and then opening the Work inbox, I noticed that there was one blank item in the "My current" left hand side list view (see image).  This item is dated 18 May 2018 but has no traffic light symbol and no title. 

The full dataset needs to be displayed for each item, there should be no blank fields.

![screen shot 2018-05-16 at 16 29 37](https://user-images.githubusercontent.com/2330529/40127326-06555f80-5927-11e8-99af-9ed3b17f6de1.png)

**Comment by Dartv** [comment] 2018-05-18 12:32
Duplicate of https://github.com/Pliohub/Plio/issues/1084

**Closed** 2018-06-29 13:13 UTC
Labels: bug, resolved
