### ISSUE TITLE
Key partners -> adding files

### ISSUE THREAD

**Issue by MaxLutkovec** [Pliohub/Plio#1652] opened 2018-12-18 11:35 UTC
Chrome Web
1. Create key partners
2. Open created key partners
3. Add files -> Close key partners
4. Open this key partners 
Expected result: added files displays
Actual: there no added files display (watch video from link) 
https://drive.google.com/open?id=1LLWdDnJ8WEvMm5q_cMUEIg3W7nn_7i0d

**Comment by Dartv** [comment] 2018-12-18 11:35
Duplicate of https://github.com/Pliohub/Plio/issues/1565

**Closed** 2019-01-15 16:39 UTC
Labels: bug, duplicate
