### ISSUE TITLE
The error  message and invalid data is presented after creating standard

### ISSUE THREAD

**Issue by RustamJS** [Pliohub/Plio#1015] opened 2018-05-07 14:50 UTC
**Steps to reproduce:**

1. Open the "Standards - deleted" page 
2. Click to "Add" button
3. Create the standard with valid data  
**Expected result:**

A new standard created successfully  without irrelevant data

**Actual result:**

The error message appears and irrelevant CA and PA are present

https://drive.google.com/file/d/13qQSwmGyoQnyJ_V9w9tJLFfPlsIla8Df/view?usp=sharing

**Comment by Dartv** [comment] 2018-05-08 13:38
Super strange. I dunno why it happened and I couldn't reproduce this either, but there was a another bug.
You weren't redirected to that standard. Shouldn't happen anymore.
https://github.com/Pliohub/Plio/pull/1024

**Comment by RustamJS** [comment] 2018-05-08 14:12
@Dartv Try to reproduce it on Chrome and FireFox  (except Safari and Edge), see below 

https://drive.google.com/file/d/1Ne6AyviJiNBxU4E39OOzGfOZpjA4yVMY/view?usp=sharing

**Comment by Dartv** [comment] 2018-05-09 09:34
Cannot reproduce this on either chrome or firefox, I think it should be fixed already.

**Comment by RustamJS** [comment] 2018-05-17 19:29
I can show how reproduce this one .

**Closed** 2018-06-29 13:14 UTC
Labels: Apiko QA, bug, can't be reproduced, resolved

**Comment by Dartv** [comment] 2018-06-30 03:10
via Hubstaff
User: Dmytro Artamonov

Project: Plio Connected - https://app.hubstaff.com/projects/329669
Date Range: 05/08/18 - 05/08/18
Work session total: 0:57:18

Grand total: 0:57:18
